
notifications:
  email:
    recipients:
      - pg8p@virginia.edu
    on_success: always
    on_failure: always
sudo: false
cache:
  apt: true
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
language: cpp
install:
  # Linux prerequisite steps 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq install build-essential cmake libboost-all-dev libgtest-dev libssl-dev lcov ggcov gdb; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cmake boost ; fi
before_script:
   # gtest install workaround
   - wget http://googletest.googlecode.com/files/gtest-1.7.0.zip
   - tar -xvzf gtest-1.7.0.zip
   - cd gtest-1.7.0
   - cmake .
   - make
   - export GTEST_ROOT="`pwd`"
   - cd ..
   # -- workaround end
script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_GUI_TESTS=ON ..
  - make
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make test ARGS+="-E testgui"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make test; fi
